### ISSUE TITLE
Source code for Do_CCF_New?

### ISSUE THREAD

**Issue by mca-sh** [AndersBarth/TraceCorrelationAnalysis#1]
Hello Anders,
Would it be possible to have access to the source file `Do_CCF_New`?
I am trying to calculate cross-correlation functions of donor and acceptor TIRF trajectories in non-linear mode but the compiled mex file `Do_CCF_new.mexw64` is not working on my setup. I would need to recompile it.
Thanks,
Mélodie

**Comment by AndersBarth** [comment]
Hi Mélodie,

indeed, seems I forgot to include the source files there. They are available in the PAM software package, which is where I took this general routine from.
Please find it attached. 

And let me know in case there are any other issues!

Best,
Anders

￼

**Comment by mca-sh** [comment]
Great thank you!
Email attachment are not transmitted via Github, but I found it in your PIE-PAM repo.
All the best,
Mélodie
